public with sharing class FileUpload {
	public Document document {get; set;}
	public String url {get; set;}
	public boolean hasImage {get; set;}
	
	public FileUpload() {
		hasImage = false;
		document = new document();
		if (SiteImageBrowser.isImage == null){
			SiteImageBrowser.isImage = false;
		}
	}

	public PageReference doUpload() {

		if (document.body != null) {
	        System.debug('@@@@@@@@ document:' + document.name);
	        
	        if (document.name != null) {
		     	System.debug('@@@@@@@@ doSave');
		        
		        Document d = document;
		        System.debug(document);
		        System.debug('@@@@@@@@ document name: '+d.name);
		        System.debug(d);
				
				
		        d.IsPublic = true;
		        System.debug('@@@@@@@@ doc type is ' +d.ContentType);
		        if (d.ContentType == 'image/png' || d.ContentType == 'image/jpg' || d.ContentType == 'image/jpeg' || d.ContentType == 'image/gif'){
					SiteImageBrowser.isImage = true;
				} else {
					if (d.Name.contains('.jpg') || d.Name.contains('.jpeg')){
						SiteImageBrowser.isImage = true;
						d.ContentType = 'image/jpg';	
					}
					if (d.Name.contains('.gif')){
						SiteImageBrowser.isImage = true;
						d.ContentType = 'image/gif';
					}
					if (d.Name.contains('.png')){
						SiteImageBrowser.isImage = true;
						d.ContentType = 'image/png';
					} 
					if (d.Name.contains('.tif') || d.Name.contains('.tiff')){
						SiteImageBrowser.isImage = true;
						d.ContentType = 'image/tif';
					} 
					/*
					if (d.Name.contains('.doc')){
						d.ContentType = 'application/msword';
					}
					if (d.Name.contains('.docx')){
						d.ContentType = 'application/msword';
					}
					if (d.Name.contains('.xls')){
						d.ContentType = 'application/excel';
					}
					if (d.Name.contains('.xlsx')){
						d.ContentType = 'application/excel';
					}
					if (d.Name.contains('.rtf')){
						d.ContentType = 'application/rtf';
					}
					if (d.Name.contains('.pdf')){
						d.ContentType = 'application/pdf';
					}
					if (d.Name.contains('.ppt')){
						d.ContentType = 'application/mspowerpoint';
					}
					if (d.Name.contains('.pptx')){
						d.ContentType = 'application/mspowerpoint';
					}	
					if (d.Name.contains('.txt')){
						d.ContentType = 'text/plain';
					}*/
					
					if (SiteImageBrowser.isImage == null){
						SiteImageBrowser.isImage = false;
					}
				}
				
				Id idFolder = [Select Id from Folder where DeveloperName = 'VSB_Web_Event_Graphics'][0].Id;
		        d.folderid = idFolder; //store in Personal Documents
		        System.debug('@@@@@@@@ document folder id: '+d.folderid);
		        
		        try {
		        	insert d;
		        	url = DocumentUtil.getInstance().getURL(d);
		        	hasImage = true;
		        } catch (Exception e) {
		        	ApexPages.addMessages(e);
		        	url = '';
		        }
		        
		        d.body = null;
		        
		        
		    	
		        System.debug('@@@@@@@@ document object id: '+d.id);
		        String url = DocumentUtil.getInstance(d).getURL();
		        System.debug('######## document content type: '+d.type);        
	        }
		        
	
	    }
     	
     	PageReference page = new PageReference('/apex/FileUpload');
        //page.setRedirect(true);
        return page;   
	}
	
	static testmethod void testFileUpload() {
		FileUpload fu = new FileUpload();
		fu.doUpload();
		
		fu.document.Name = 'test1';
		fu.document.Body = Blob.valueOf('test1'); 
		
		fu.doUpload();
		
	}
	
}